interface ZIF_CDS_45_LOGALI_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCDS_45_LOGALI,
 CREATE_ZCDS_45_LOGALI          TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5C01FFD185DB',
 DELETE_ZCDS_45_LOGALI          TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5C01FFD205DB',
 LOCK_ZCDS_45_LOGALI            TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5BD7E17A25DB',
 SAVE_ZCDS_45_LOGALI            TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5C01FFD285DB',
 UNLOCK_ZCDS_45_LOGALI          TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5BD7E17A65DB',
 UPDATE_ZCDS_45_LOGALI          TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5C01FFD1C5DB',
 VALIDATE_ZCDS_45_LOGALI        TYPE /BOBF/ACT_KEY VALUE '000C292775F91EECB0AA5C01FFD245DB',
      END OF ZCDS_45_LOGALI,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCDS_45_LOGALI,
        BEGIN OF LOCK_ZCDS_45_LOGALI,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZCDS_45_LOGALI,
        BEGIN OF UNLOCK_ZCDS_45_LOGALI,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZCDS_45_LOGALI,
      END OF ZCDS_45_LOGALI,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCDS_45_LOGALI,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292775F91EECB0AA5BD7E17A05DB',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292775F91EECB0AA5BD7E179C5DB',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292775F91EECB0AA5BD7E17AC5DB',
      END OF ZCDS_45_LOGALI,
      BEGIN OF ZCDS_45_LOGALI_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292775F91EECB0AA5C01FFD2E5DB',
      END OF ZCDS_45_LOGALI_LOCK,
      BEGIN OF ZCDS_45_LOGALI_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292775F91EECB0AA5C01FFD2C5DB',
      END OF ZCDS_45_LOGALI_MESSAGE,
      BEGIN OF ZCDS_45_LOGALI_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292775F91EECB0AA5C01FFD305DB',
      END OF ZCDS_45_LOGALI_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCDS_45_LOGALI,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCDS_45_LOGALI,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C292775F91EECB0AA5BB1D748A5DB' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCDS_45_LOGALI' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCDS_45_LOGALI,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C292775F91EECB0AA5C8A53A265DC',
      END OF ZCDS_45_LOGALI,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZCDS_45_LOGALI                 TYPE /BOBF/OBM_GROUP_KEY VALUE '000C292775F91EECB0AA5CCD1D5A65DC',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCDS_45_LOGALI                 TYPE /BOBF/OBM_NODE_KEY VALUE '000C292775F91EECB0AA5BB1D748E5DB',
 ZCDS_45_LOGALI_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE '000C292775F91EECB0AA5BD7E179E5DB',
 ZCDS_45_LOGALI_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE '000C292775F91EECB0AA5BD7E179A5DB',
 ZCDS_45_LOGALI_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE '000C292775F91EECB0AA5BD7E17AA5DB',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCDS_45_LOGALI,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CARRNAME                       TYPE STRING VALUE 'CARRNAME',
  CURRCODE                       TYPE STRING VALUE 'CURRCODE',
  URL                            TYPE STRING VALUE 'URL',
      END OF ZCDS_45_LOGALI,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCDS_45_LOGALI,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C292775F91EECB0AA5BD7E17985DB',
      END OF ZCDS_45_LOGALI,
    END OF SC_NODE_CATEGORY .
endinterface.
